TUGAS MACHINE LEARNING

SOAL 1 Buatlah identitas diri menggunakan pemograman python sederhana

In [1]:
nama = "Zaidan Jainul Insan"
nomor_induk_mahasiswa = "20230801421"
program_studi = "Teknik Informatika"
fakultas = "Ilmu Komputer"

print("DATA DIRI")
print("Nama : ", nama)
print("NIM : ", nomor_induk_mahasiswa)
print("Program Studi : ", program_studi)
print("Fakultas :", fakultas)

DATA DIRI
Nama :  Zaidan Jainul Insan
NIM :  20230801421
Program Studi :  Teknik Informatika
Fakultas : Ilmu Komputer


SOAL 2 Buatlah matriks C dengan orde 2x3, dan nilai yang diberikan pada matriks C adalah sebagai berikut :

In [2]:
matriksC= [[1,2,3],[4,5,6]]
print(matriksC)

[[1, 2, 3], [4, 5, 6]]


SOAL 3 Buatlah matriks dengan orde 3x2, dengan nilai adalah :

Baris 1 Kolom 1, nilai = 2
Baris 1 Kolom 2, nilai = 2
Baris 2 Kolom 1, nilai = 2
Baris 2 Kolom 2, nilai = 2
Baris 3 Kolom 1, nilai = 2
Baris 3 Kolom 2, nilai = 2

In [3]:
matriks = [[2,2],[2,2],[2,2]]
print(matriks)

[[2, 2], [2, 2], [2, 2]]


SOAL 4 Importlah library Numpy

In [4]:
import numpy as np

SOAL 5 Dengan memanfaatkan library numpy Buatlah matriks dengan menggunakan Library Numpy dengan panjang elemen adalah 32 dan matriks memiliki orde 4x8

In [5]:
from numpy import *
matriks = range(32)
matriks = reshape(matriks, (4,8))
print(matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


SOAL 6 Buatlah matriks dengan menggunakan Library Numpy dengan orde 3x30, dan nilai elemen dimulai dari indeks 1 sampai dengan 5 secara random

In [6]:
import numpy as np
from numpy import *

matriks = np.random.randint(1,5,(3,30))
print(matriks)

[[3 2 1 4 4 1 4 4 4 3 2 1 4 4 1 4 4 3 1 2 1 3 3 1 2 4 4 2 3 4]
 [4 1 4 1 2 2 2 4 3 3 4 2 3 2 1 4 4 1 1 4 4 4 4 4 2 1 1 4 4 3]
 [4 4 2 1 3 2 3 3 3 2 3 4 3 3 1 4 2 2 3 2 3 1 1 4 3 2 1 2 1 2]]
